/**
 * gen-descriptions — scans descriptions/ directory, reads .feature files,
 * and generates index.ts with inlined string content.
 *
 * Convention:
 *   descriptions/{system}/{name}.feature
 *   - If name === system → system-level description (key: "system")
 *   - Otherwise → process-level description (key: name)
 *   - "world" directory is special: all files are topic entries (no "system" key)
 *
 * Run: bun run gen:desc
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const descDir = join(__dirname, "..", "src", "descriptions");

// Scan system directories
const dirs = readdirSync(descDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

// Collect structure with inlined content
const structure: Record<string, { system?: string; entries: [string, string][] }> = {};

let featureCount = 0;

for (const dir of dirs) {
  const files = readdirSync(join(descDir, dir))
    .filter((f) => f.endsWith(".feature"))
    .sort();

  structure[dir] = { entries: [] };

  for (const file of files) {
    const name = basename(file, ".feature");
    const content = readFileSync(join(descDir, dir, file), "utf-8");
    const escaped = JSON.stringify(content);
    featureCount++;

    if (dir !== "world" && name === dir) {
      structure[dir].system = escaped;
    } else {
      structure[dir].entries.push([name, escaped]);
    }
  }
}

// Generate output
const lines: string[] = [];

lines.push(`/**`);
lines.push(` * descriptions — AUTO-GENERATED by scripts/gen-descriptions.ts`);
lines.push(` *`);
lines.push(` * DO NOT EDIT MANUALLY. Run \`bun run gen:desc\` to regenerate.`);
lines.push(` *`);
lines.push(` * Source: descriptions/{system}/{process}.feature (${featureCount} files)`);
lines.push(` */`);
lines.push(``);

// World topics (special)
if (structure.world) {
  const topics = structure.world.entries;
  lines.push(`export const WORLD_TOPICS = [`);
  for (const [name] of topics) {
    lines.push(`  "${name}",`);
  }
  lines.push(`] as const;`);
  lines.push(``);
  lines.push(`export type WorldTopic = (typeof WORLD_TOPICS)[number];`);
  lines.push(``);
  lines.push(`export const world: Record<WorldTopic, string> = {`);
  for (const [name, content] of topics) {
    lines.push(`  ${name}: ${content},`);
  }
  lines.push(`};`);
  lines.push(``);
}

// System exports
for (const [dir, { system, entries }] of Object.entries(structure)) {
  if (dir === "world") continue;

  lines.push(`export const ${dir} = {`);
  if (system) {
    lines.push(`  system: ${system},`);
  }
  for (const [name, content] of entries) {
    lines.push(`  ${name}: ${content},`);
  }
  lines.push(`} as const;`);
  lines.push(``);
}

writeFileSync(join(descDir, "index.ts"), lines.join("\n"));
console.log(`Generated descriptions/index.ts (${featureCount} features inlined)`);
