/**
 * Bun Build Script for @rolexjs/core
 * ESM-only modern build
 *
 * Steps:
 * 1. Bundle role.type.ts into code string
 * 2. Generate roleType.ts with bundled code
 * 3. Build the package
 */

import { dts } from "bun-dts";
import { resolve } from "node:path";

const pkg = await Bun.file("./package.json").json();
const outdir = "./dist";

await Bun.$`rm -rf ${outdir}`;

console.log(`Building @rolexjs/core v${pkg.version}\n`);

// Step 1: Bundle role.type.ts
console.log("Bundling role type...");

const roleTypePath = resolve(import.meta.dir, "./src/builtins/role.type.ts");

const bundleResult = await Bun.build({
  entrypoints: [roleTypePath],
  target: "browser", // V8 compatible for sandbox
  format: "esm",
  minify: false,
});

if (!bundleResult.success) {
  console.error("Failed to bundle role.type.ts:");
  for (const log of bundleResult.logs) console.error(log);
  process.exit(1);
}

const bundledCode = await bundleResult.outputs[0].text();

// Import metadata from source
const mod = await import(roleTypePath);
const meta = mod.default;

console.log(`  - role: bundled`);

// Step 2: Generate roleType.ts
console.log("\nGenerating roleType.ts...");

/**
 * Process ESM bundled code for sandbox execution.
 */
function processEsmBundle(bundledCode: string): { code: string; varName: string } {
  // Extract variable name from: export { X as default };
  const exportMatch = bundledCode.match(/export\s*\{\s*(\w+)\s+as\s+default\s*\}/);
  if (!exportMatch) {
    throw new Error("Could not find default export in bundled code");
  }
  const varName = exportMatch[1];

  // Remove the export statement
  const code = bundledCode.replace(/export\s*\{\s*\w+\s+as\s+default\s*\};\s*/g, "").trim();

  return { code, varName };
}

const { code, varName } = processEsmBundle(bundledCode);
// Escape backticks and ${} in the code for template literal
const escapedCode = code.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const roleTypeContent = `/**
 * Role Resource Type (pre-bundled)
 * Auto-generated by build.ts - DO NOT EDIT
 *
 * Resolver code receives ResolveContext (ctx) with:
 * - ctx.manifest: { registry?, path?, name, type, version }
 * - ctx.files: Record<string, Uint8Array>
 */

import type { BundledType } from "resourcexjs";

/**
 * ${meta.description}
 */
export const roleType: BundledType = {
  name: "${meta.name}",
  aliases: ${JSON.stringify(meta.aliases)},
  description: "${meta.description}",
  code: \`// @resolver: ${varName}
${escapedCode}\`,
};
`;

await Bun.write("./src/roleType.ts", roleTypeContent);
console.log("  - roleType.ts generated");

// Step 3: Build the package
console.log("\nBuilding package...");

const result = await Bun.build({
  entrypoints: ["src/index.ts"],
  outdir,
  format: "esm",
  target: "node",
  sourcemap: "external",
  minify: false,
  plugins: [dts()],
  external: ["resourcexjs", "dpml"],
  define: {
    __VERSION__: JSON.stringify(pkg.version),
  },
});

if (!result.success) {
  console.error("Build failed:");
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

console.log(`\nBuild complete: ${result.outputs.length} files`);
